language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: ultraton
  api_key:
    secure: T1S6r8rbSGloDQBjoN5LKJEn8X4IvI/CLIj290eo0emyj6sXmKobfEeOYPbGhKndfO9Vo8J3jR0M2zQBLU7p6X5RpUG3CavAEhmUjToO0CPgnMy5A9hTeLEzBGQxBInrrI8r+sGXsHJeRdeMdwLgxucvPz4uIsjkk+dn7Hab11Rghqtsnxp8D9EerZqSyBwAYkqZF2yn061JfZlHD+cqQWGexZdvN8Yi0XDunnhjZ2x/2zkYTFQ0q/KrJr6woFGMuPmiVaN/hLoptGMb4geLHN93ip3+n3jjXNnKtZt48EGUka1n3CRKd8lVOpMmlDQCXvpo/URHTzLRlO1I4gyqtWf4WDu1qqY4fGPlvHK5cdDGhrABUUziQyMsgVManZP/AFQXGU64jrEKfdQlce/dm1aEERr8dDOtlCcDHxg58A4KNIGBrcDveo/juW8Rq2CwkxBEKR1aYdAeecVdplgBoTbKNf7+ooBwL3zaYvbVc5TLbF11IVd3MP7sXzR0FkNfWSlftKehlVGFZhA3ICAloTBFFC+eogg6F8fSrxzgn4VHLSaSDqHFmfVhTW5DQwSQSNpx1BAWHnJB1bFsUG0IC/cHwsLeDqU2lVCC+PoFBMdUd1WxASD4OZW+N1H5uYLutjZ7aJ21sxPhHN4efm5jIkoZm2564VcByZEEFjdXaUY=
  on: master
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
